# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 364)
        MainWindow.setStyleSheet("background-color:rgb(53, 53, 53);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.proceedButt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proceedButt.sizePolicy().hasHeightForWidth())
        self.proceedButt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.proceedButt.setFont(font)
        self.proceedButt.setStyleSheet("background-color: rgb(208, 145, 90)")
        self.proceedButt.setObjectName("proceedButt")
        self.gridLayout_2.addWidget(self.proceedButt, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.passLine = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passLine.sizePolicy().hasHeightForWidth())
        self.passLine.setSizePolicy(sizePolicy)
        self.passLine.setStyleSheet("background-color:rgb(206, 164, 114)")
        self.passLine.setObjectName("passLine")
        self.gridLayout_2.addWidget(self.passLine, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuAutosave_3 = QtWidgets.QMenu(self.menuFile)
        self.menuAutosave_3.setObjectName("menuAutosave_3")
        self.menuAutosave = QtWidgets.QMenu(self.menubar)
        self.menuAutosave.setObjectName("menuAutosave")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionin_database = QtWidgets.QAction(MainWindow)
        self.actionin_database.setObjectName("actionin_database")
        self.actionin_local_file_csv = QtWidgets.QAction(MainWindow)
        self.actionin_local_file_csv.setObjectName("actionin_local_file_csv")
        self.actionOn = QtWidgets.QAction(MainWindow)
        self.actionOn.setObjectName("actionOn")
        self.actionOff = QtWidgets.QAction(MainWindow)
        self.actionOff.setObjectName("actionOff")
        self.actionboth = QtWidgets.QAction(MainWindow)
        self.actionboth.setObjectName("actionboth")
        self.menuSave.addSeparator()
        self.menuSave.addAction(self.actionin_database)
        self.menuSave.addAction(self.actionin_local_file_csv)
        self.menuSave.addAction(self.actionboth)
        self.menuAutosave_3.addAction(self.actionOn)
        self.menuAutosave_3.addAction(self.actionOff)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.menuAutosave_3.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAutosave.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.proceedButt.setText(_translate("MainWindow", "Proceed"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuAutosave_3.setTitle(_translate("MainWindow", "Autosave"))
        self.menuAutosave.setTitle(_translate("MainWindow", "Autosave"))
        self.actionin_database.setText(_translate("MainWindow", "in database"))
        self.actionin_local_file_csv.setText(_translate("MainWindow", "in local file (.csv)"))
        self.actionOn.setText(_translate("MainWindow", "On"))
        self.actionOff.setText(_translate("MainWindow", "Off"))
        self.actionboth.setText(_translate("MainWindow", "both"))

